apiVersion: app/v1
kind: Deployment
metadata:
  name: streamlit-app
  labels:
    app: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit-container
          image: streamlit-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8501

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer
  selector:
    app: streamlit
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8501
